### ISSUE TITLE
Add : Submitted attributes to change model.

### ISSUE THREAD

**Issue by preethamraj27** [shijl0925/python-gerrit-api#16]
Hi, 
We use the submitted field on the ChangeInfo response thats returned by GET /changes. 

Pls can you add the 'submitted' attribute to the GerritChange Model ? It would be great !

Also, Pls do consider adding all the conditional/optional Fields to the GerritChange Model ? 

Thx
PR

**Comment by shijl0925** [comment]
I have add the Submitted attributes to change model,  please use the version 1.0.6 package.
