### ISSUE TITLE
Does anyone know the mapping gerrit REST API version?

### ISSUE THREAD

**Issue by haibinzero** [shijl0925/python-gerrit-api#18]
Thank you for the good and simple code for Gerrit interactions, could you note which Gerrit REST API version is used? 
For the Gerrit REST API model there are some optional fields that can be queried by adding &o= in the query URL, seems the recent code (model and method) does not support the optional fields.

**Comment by shijl0925** [comment]
Project tested on Version 3.1.8 Gerrit.

**Comment by shijl0925** [comment]
the optional fields will support in version 1.0.8.
https://github.com/shijl0925/python-gerrit-api/commit/32fa4f67d43f795f5996ab9cbaf9abb7558a0d78
