### ISSUE TITLE
During cherry-pick please map the source change id to destination change id

### ISSUE THREAD

**Issue by arun-421** [shijl0925/python-gerrit-api#21]
During gerrit cherry pick, the change id in destination branch is getting changed and it is impossible track as well.

**Comment by shijl0925** [comment]
`
input_ = {
    "message" : "Implementing Feature X",
    "destination" : "release-branch"
}

source_change_id = 'Project~stable~I10394472cbd17dd12454f229e4f6de00b143a444'
change = client.changes.get(source_change_id)
revision = change.get_revision('3848807f587dbd3a7e61723bbfbf1ad13ad5a00a')
result = revision.cherry_pick(input_)
dest_change_id = result.get("id")
`

**Comment by NaveenTamatam** [comment]
@shijl0925 Same issue happens while we are trying to cherry pick like below,

input_ = {
"message" : "Implementing Feature X",
"destination" : "release-branch"
}
comm = project.get_commit(commit_id)
comm.cherry_pick(input_)

Can you please help us how to overcome this? We are using 3.0.8 version gerrit module.

Thanks,
Naveen.
