### ISSUE TITLE
Gerrit - fetching file shows AttributeError: type object 'GerritChangeRevisionFile' has no attribute 'parse'

### ISSUE THREAD

**Issue by sabareesh-m** [shijl0925/python-gerrit-api#27]
revision = change.get_revision(latest_rev_id)
file = revision.files.get('pom.xml')

throws, 
...\Python\Python39\lib\site-packages\gerrit\changes\revision\files.py", line 164, in __getitem__
    return GerritChangeRevisionFile.parse(
AttributeError: type object 'GerritChangeRevisionFile' has no attribute 'parse'

**Comment by shijl0925** [comment]
version 2.1.4 has been released. fix the issue
