### ISSUE TITLE
Issue with RevisionDrafts Endpoint Initialization

### ISSUE THREAD

**Issue by ritvik0611** [shijl0925/python-gerrit-api#35]
https://github.com/shijl0925/python-gerrit-api/blob/5a01f2d958eea2abba73e10ae1ba9c251d254eb5/gerrit/changes/revision/drafts.py#L55

Do not need to retrieve anything from Gerrit to initialize the endpoint- can directly set the format string the way it is done for GerritChangeRevisionDraft. See below:

https://github.com/shijl0925/python-gerrit-api/blob/5a01f2d958eea2abba73e10ae1ba9c251d254eb5/gerrit/changes/revision/drafts.py#L13

**Comment by shijl0925** [comment]
https://github.com/shijl0925/python-gerrit-api/commit/d4b92297eec4ab660c6343b7a146a39c828aa05e

this bug fixed in 3.0.1
