### ISSUE TITLE
Query change isn't working

### ISSUE THREAD

**Issue by spicollys** [shijl0925/python-gerrit-api#7]
Hello, I notice that GerritChanges.search method isn't working, is returning an error.
I looked your code and I think that changing the line 17: 
`endpoint = "/changes/?%s" % query`
to
`endpoint = "/changes/?q=%s" % query`
will resolve the problem.
Regards,
Lucas Spicollys

**Comment by shijl0925** [comment]
It is not a bug.

example code:
change = gerrit.changes.search('q=status:open')
